### ISSUE TITLE
How can I install ns3-gym in centos

### ISSUE THREAD

**Issue by Leinlix** [tkn-tub/ns3-gym#15]

**Comment by pgawlowicz** [comment]
Hi, 
Unfortunately, due to the limited time, I cannot provide installation descriptions for all Linux versions.
Probably, you have to follow the description here:
https://www.nsnam.org/wiki/Installation#CentOS

and then install ns3gym dependencies including libzmq5 libzmq5-dev libprotobuf-dev protobuf-compiler

once you have your installation ready, you can provide installation description for ns3-gym readme file.

Thanks,
Piotr
